## Assignment 4June2020

In [12]:
#1.Write a NumPy program to reverse an array (first element becomes last). 
import numpy as z
aq=z.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
aq[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [24]:
#2.Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
import numpy as x
n1=int(input("Enter number of columns "))
n2=int(input("Enter number of rows "))
aw=x.ones((n1,n2))
print("Original Matrix ")
print(aw)
print("Modified Matrix ")
aw[1:-1,1:-1]=0
print(aw)

Enter number of columns 4
Enter number of rows 5
Original Matrix 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Modified Matrix 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
#3.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
import numpy as y
y.in1d([0,10,20,40,60],[0,20])

array([ True, False,  True, False, False])

In [39]:
#4.Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
import numpy as y
y.setdiff1d([ 0,10,20,40,60,80]
,[10, 30, 40, 50, 70, 90] )

array([ 0, 20, 60, 80])

In [70]:
#5.Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
import numpy as x
a = np.zeros((4,4))
print("Original Matrix ")
print(a)
print("Modified Matrix ")
x.fill_diagonal(a, [4, 5, 6, 8])
a

Original Matrix 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Modified Matrix 


array([[4., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 8.]])